---
kind: pipeline
type: kubernetes
name: ci
clone:
  depth: 1
  disable: true

steps:
  - name: 获取代码
    image: ccr.ccs.tencentyun.com/easycorp/drone-plugin-git
    pull: always
    settings:
      depth: 1
      branch: ${DRONE_BRANCH}
      url: git@git.external-prod.chandao.net:pangu/qcadmin.git

  - name: download k3s
    image: ccr.ccs.tencentyun.com/easycorp/drone-plugin-shell
    pull: always
    privileged: true
    commands:
      - wget -O /drone/src/hack/bin/k3s-linux-amd64 https://pkg-1308438674.cos.ap-shanghai.myqcloud.com/qucheng/cli/stable/k3s/v1.24.11/k3s-linux-amd64
      - wget -O /drone/src/hack/bin/k3s-linux-arm64 https://pkg-1308438674.cos.ap-shanghai.myqcloud.com/qucheng/cli/stable/k3s/v1.24.11/k3s-linux-arm64
      - chmod +x /drone/src/hack/bin/k3s-linux-amd64 /drone/src/hack/bin/k3s-linux-arm64

  - name: build
    image: ccr.ccs.tencentyun.com/easycorp/drone-plugin-gox
    pull: always
    privileged: true
    commands:
      - make generate
      - make build

  - name: upx bin
    image: ysicing/drone-plugin-upx
    privileged: true
    pull: always
    settings:
      debug: true
      path: ./dist
      include: amd64

  - name: upload stable
    image: ysicing/drone-plugin-cos
    privileged: true
    pull: always
    settings:
      debug: true
      region: ap-shanghai
      bucket:
        from_secret: s3-bucket
      accesskey:
        from_secret: s3-access-key
      secretkey:
        from_secret: s3-secret-key
      source: ./dist
      target:
        from_secret: s3-stable-path
    when:
      event:
      - tag

  - name: upload edge
    image: ysicing/drone-plugin-cos
    privileged: true
    pull: always
    settings:
      debug: true
      region: ap-shanghai
      autotime: false
      bucket:
        from_secret: s3-bucket
      accesskey:
        from_secret: s3-access-key
      secretkey:
        from_secret: s3-secret-key
      source: ./dist
      target:
        from_secret: s3-edge-path
    when:
      branch:
      - master

  # - name: upload edge install
  #   image: ysicing/drone-plugin-cos
  #   privileged: true
  #   pull: always
  #   settings:
  #     debug: true
  #     region: ap-shanghai
  #     autotime: false
  #     bucket:
  #       from_secret: s3-bucket
  #     accesskey:
  #       from_secret: s3-access-key
  #     secretkey:
  #       from_secret: s3-secret-key
  #     source: ./hack/scripts/get.sh
  #     target:
  #       from_secret: s3-edge-path
  #   when:
  #     branch:
  #     - master

  - name: release stable version
    image: ysicing/drone-plugin-rv
    privileged: true
    pull: always
    settings:
      name: qcadmin
      url:
        from_secret: rv-url
      token:
        from_secret: qc-token
      type: stable
    when:
      event:
      - tag

  # - name: release edge version
  #   image: ysicing/drone-plugin-rv
  #   privileged: true
  #   pull: always
  #   settings:
  #     name: qcadmin
  #     url:
  #       from_secret: rv-url
  #     token:
  #       from_secret: qc-token
  #     type: edge
  #   when:
  #     branch:
  #     - master

# services:
#   - name: docker daemon
#     image: ccr.ccs.tencentyun.com/easycorp/drone-plugin-dockerd
#     privileged: true
#     volumes:
#       - name: dockersock
#         path: /var/run

# volumes:
#   - name: dockersock
#     temp: {}

node_selector:
  workload_type: "spot"

tolerations:
  - key: ci.zcorp.cc
    operator: Exists
    effect: NoSchedule
