# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
env:
  - GO111MODULE=on

# gomod:
#   proxy: true

before:
  hooks:
    - make generate
    - ./hack/scripts/gencompletions.sh
    - ./hack/scripts/genmanpages.sh
    # - make default
builds:
  - ldflags:
      - -w -s -X github.com/easysoft/qcadmin/common.Version={{.Summary}}
      - -X github.com/easysoft/qcadmin/common.BuildDate={{.CommitDate}}
      - -X github.com/easysoft/qcadmin/common.GitCommitHash={{.ShortCommit}}
      - -X k8s.io/client-go/pkg/version.gitVersion={{.Summary}}
      - -X k8s.io/client-go/pkg/version.gitCommit={{.FullCommit}}
      - -X k8s.io/client-go/pkg/version.gitTreeState=dirty
      - -X k8s.io/client-go/pkg/version.buildDate={{.CommitDate}}
      - -X k8s.io/client-go/pkg/version.gitMajor=1
      - -X k8s.io/client-go/pkg/version.gitMinor=23
      - -X k8s.io/component-base/version.gitVersion={{.Summary}}
      - -X k8s.io/component-base/version.gitCommit={{.FullCommit}}
      - -X k8s.io/component-base/version.gitTreeState=dirty
      - -X k8s.io/component-base/version.gitMajor=1
      - -X k8s.io/component-base/version.gitMinor=23
      - -X k8s.io/component-base/version.buildDate={{.CommitDate}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      # - mips
      # - mipsle
      # - s390x
      # - riscv64
    # gomips:
    #   - softfloat
    hooks:
      post:
        - upx -9 -f -q "{{ .Path }}"
    main: main.go
    binary: qcadmin
  - id: macos-build
    ldflags:
      - -w -s -X github.com/easysoft/qcadmin/common.Version={{.Summary}}
      - -X github.com/easysoft/qcadmin/common.BuildDate={{.Date}}
      - -X github.com/easysoft/qcadmin/common.GitCommitHash={{.ShortCommit}}
      - -X k8s.io/client-go/pkg/version.gitVersion={{.Summary}}
      - -X k8s.io/client-go/pkg/version.gitCommit={{.FullCommit}}
      - -X k8s.io/client-go/pkg/version.gitTreeState=dirty
      - -X k8s.io/client-go/pkg/version.buildDate={{.Date}}
      - -X k8s.io/client-go/pkg/version.gitMajor=1
      - -X k8s.io/client-go/pkg/version.gitMinor=23
      - -X k8s.io/component-base/version.gitVersion={{.Summary}}
      - -X k8s.io/component-base/version.gitCommit={{.FullCommit}}
      - -X k8s.io/component-base/version.gitTreeState=dirty
      - -X k8s.io/component-base/version.gitMajor=1
      - -X k8s.io/component-base/version.gitMinor=23
      - -X k8s.io/component-base/version.buildDate={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
      # - mips
      # - mipsle
      # - s390x
      # - riscv64
    # gomips:
    #   - softfloat
    # ignore:
    #   - goos: darwin
    #     goarch: mips
    #   - goos: darwin
    #     goarch: mipsle
    #   - goos: darwin
    #     goarch: s390x
    #   - goos: darwin
    #     goarch: riscv64
    main: main.go
    binary: qcadmin
# universal_binaries:
#   - name_template: "qcadmin"
#     replace: false
archives:
  - format: binary
    name_template: "qcadmin_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-snapshot-{{.ShortCommit}}"

nfpms:
- file_name_template: 'qcadmin_{{ .Tag }}_{{ .Os }}_{{ .Arch }}'
  homepage: https://www.qucheng.com
  version_metadata: git
  description: |-
    Cloud Native application delivery platform cli
  maintainer: qucheng
  license: MIT
  vendor: https://github.com/easysoft/qucheng_cli
  formats:
  # - apk
  - deb
  - rpm
  bindir: /usr/bin
  section: utils
  contents:
    - src: /usr/bin/qcadmin
      dst: /usr/bin/q
      type: symlink
    - src: ./completions/q.bash
      dst: /usr/share/bash-completion/completions/q
      file_info:
        mode: 0644
        owner: notRoot
        group: notRoot
    - src: ./completions/q.fish
      dst: /usr/share/fish/completions/q.fish
      file_info:
        mode: 0644
        owner: notRoot
        group: notRoot
    - src: ./completions/q.zsh
      dst:  /usr/share/zsh/vendor-completions/_q
      file_info:
        mode: 0644
        owner: notRoot
        group: notRoot
    - src: ./manpages/q.1.gz
      dst: /usr/share/man/man1/q.1.gz
      file_info:
        mode: 0644
        owner: notRoot
        group: notRoot
    - src: ./LICENSE.md
      dst: /usr/share/doc/q/copyright
      file_info:
        mode: 0644
        owner: notRoot
        group: notRoot
    - src: ./completions/qcadmin.bash
      dst: /usr/share/bash-completion/completions/qcadmin
      file_info:
        mode: 0644
        owner: notRoot
        group: notRoot
    - src: ./completions/qcadmin.fish
      dst: /usr/share/fish/completions/qcadmin.fish
      file_info:
        mode: 0644
        owner: notRoot
        group: notRoot
    - src: ./completions/qcadmin.zsh
      dst:  /usr/share/zsh/vendor-completions/_qcadmin
      file_info:
        mode: 0644
        owner: notRoot
        group: notRoot
    - src: ./manpages/qcadmin.1.gz
      dst: /usr/share/man/man1/qcadmin.1.gz
      file_info:
        mode: 0644
        owner: notRoot
        group: notRoot
    - src: ./LICENSE.md
      dst: /usr/share/doc/qcadmin/copyright
      file_info:
        mode: 0644
        owner: notRoot
        group: notRoot
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^feat(update):'
      - '^feat(ci):'
      - '^chore(ci):'
      - '^chore(action):'
      - Merge pull request
      - Merge branch
      - go mod tidy
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999
