version: 2

project_name: qcadmin

env:
  - GO111MODULE=on

git:
  ignore_tags:
    - nightly
    - dev

before:
  hooks:
    - task generate
    - ./hack/scripts/gencompletions.sh
    - ./hack/scripts/genmanpages.sh

builds:
  - ldflags:
      - -w -s -X github.com/easysoft/qcadmin/common.Version={{.Summary}}
      - -X github.com/easysoft/qcadmin/common.BuildDate={{.CommitDate}}
      - -X github.com/easysoft/qcadmin/common.GitCommitHash={{.ShortCommit}}
      - -X k8s.io/client-go/pkg/version.gitVersion={{.Summary}}
      - -X k8s.io/client-go/pkg/version.gitCommit={{.FullCommit}}
      - -X k8s.io/client-go/pkg/version.gitTreeState=dirty
      - -X k8s.io/client-go/pkg/version.buildDate={{.CommitDate}}
      - -X k8s.io/client-go/pkg/version.gitMajor=1
      - -X k8s.io/client-go/pkg/version.gitMinor=24
      - -X k8s.io/component-base/version.gitVersion={{.Summary}}
      - -X k8s.io/component-base/version.gitCommit={{.FullCommit}}
      - -X k8s.io/component-base/version.gitTreeState=dirty
      - -X k8s.io/component-base/version.gitMajor=1
      - -X k8s.io/component-base/version.gitMinor=24
      - -X k8s.io/component-base/version.buildDate={{.CommitDate}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: main.go
    id: qcadmin
    binary: qcadmin

archives:
  - formats: [ 'binary' ]
    name_template: "qcadmin_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Version }}-snapshot-{{ .ShortCommit }}"

nfpms:
- file_name_template: 'qcadmin_{{ .Tag }}_{{ .Os }}_{{ .Arch }}'
  ids:
  - qcadmin
  package_name: qcadmin
  priority: optional
  vendor: https://github.com/easysoft/quickon_cli
  homepage: https://www.qucheng.com
  version_metadata: git
  description: |-
    Cloud Native application delivery platform cli
  maintainer: easysoft
  license: AGPL-3.0
  formats:
  - deb
  - rpm
  bindir: /usr/bin
  section: utils
  contents:
    - src: ./completions/q.bash
      dst: /usr/share/bash-completion/completions/q
      file_info:
        mode: 0644
        owner: notRoot
        group: notRoot
    - src: ./completions/q.fish
      dst: /usr/share/fish/completions/q.fish
      file_info:
        mode: 0644
        owner: notRoot
        group: notRoot
    - src: ./completions/q.zsh
      dst:  /usr/share/zsh/vendor-completions/_q
      file_info:
        mode: 0644
        owner: notRoot
        group: notRoot
    - src: ./manpages/q.1.gz
      dst: /usr/share/man/man1/q.1.gz
      file_info:
        mode: 0644
        owner: notRoot
        group: notRoot
    - src: ./LICENSE.md
      dst: /usr/share/doc/q/copyright
      file_info:
        mode: 0644
        owner: notRoot
        group: notRoot
    - src: ./completions/qcadmin.bash
      dst: /usr/share/bash-completion/completions/qcadmin
      file_info:
        mode: 0644
        owner: notRoot
        group: notRoot
    - src: ./completions/qcadmin.fish
      dst: /usr/share/fish/completions/qcadmin.fish
      file_info:
        mode: 0644
        owner: notRoot
        group: notRoot
    - src: ./completions/qcadmin.zsh
      dst:  /usr/share/zsh/vendor-completions/_qcadmin
      file_info:
        mode: 0644
        owner: notRoot
        group: notRoot
    - src: ./manpages/qcadmin.1.gz
      dst: /usr/share/man/man1/qcadmin.1.gz
      file_info:
        mode: 0644
        owner: notRoot
        group: notRoot
    - src: ./LICENSE.md
      dst: /usr/share/doc/qcadmin/copyright
      file_info:
        mode: 0644
        owner: notRoot
        group: notRoot
    - dst: /root/.qc
      type: dir
  scripts:
    preinstall: ./hack/packaging/preinstall.sh
    postinstall: ./hack/packaging/postinstall.sh
    preremove: ./hack/packaging/preremove.sh
    postremove: ./hack/packaging/postremove.sh

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^feat(ci):'
      - '^chore(ci):'
      - '^chore(action):'
      - '^Merge remote'

release:
  prerelease: auto
  replace_existing_draft: true
  mode: replace
  extra_files:
    - glob: version.json
