services:
  master:
    image: hub.zentao.net/app/mysql:8.0.33-debian-11-r11
    container_name: master
    pull_policy: if_not_present
    restart: always
    volumes:
      - 'masterdb:/bitnami/mysql/data'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=pAss4Zenta0Paas
      - MYSQL_USER=zenta0Abm1n
      - MYSQL_PASSWORD=paSs4Zenta0Pass
      - MYSQL_DATABASE=zenta0paas
      - MYSQL_CHARACTER_SET=utf8mb4
      - MYSQL_COLLATE=utf8mb4_unicode_ci
      - MYSQL_REPLICATION_MODE=master
      - MYSQL_REPLICATION_USER=repL_user
      - MYSQL_REPLICATION_PASSWORD=rep1_pASsw0rd
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s

  slave:
    image: hub.zentao.net/app/mysql:8.0.33-debian-11-r11
    container_name: slave
    pull_policy: if_not_present
    restart: always
    volumes:
      - 'slavedb:/bitnami/mysql/data'
    # ports:
    #   - '3307:3306'
    depends_on:
      - master
    environment:
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_REPLICATION_USER=repL_user
      - MYSQL_REPLICATION_PASSWORD=rep1_pASsw0rd
      - MYSQL_USER=zenta0Abm1n
      - MYSQL_PASSWORD=paSs4Zenta0Pass
      - MYSQL_DATABASE=zenta0paas
      - MYSQL_MASTER_HOST=master
      - MYSQL_MASTER_PORT_NUMBER=3306
      - MYSQL_MASTER_ROOT_PASSWORD=pAss4Zenta0Paas
      - MYSQL_CHARACTER_SET=utf8mb4
      - MYSQL_COLLATE=utf8mb4_unicode_ci
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s

volumes:
  masterdb:
  slavedb:
