name: Release

on:
  push:
    tags:
    - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.x
    - name: Cache Go Dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v3
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    - name: Publish .deb & .rpm to Gemfury
      env:
        FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
      run: |
        for filename in dist/*.deb; do
          if [[ "$filename" == *"arm"* ]]; then
            echo "Skipping $filename"
            continue
          fi
          echo "Pushing $filename to apt repository"
          curl -F package=@$filename https://${FURY_TOKEN}@push.fury.io/qucheng/
          curl -F package=@$filename https://${FURY_TOKEN}@push.fury.io/qucheng/
        done
        for filename in dist/*.rpm; do
          if [[ "$filename" == *"arm"* ]]; then
            echo "Skipping $filename"
            continue
          fi
          echo "Pushing $filename to rpm repository"
          curl -F package=@$filename https://${FURY_TOKEN}@push.fury.io/qucheng/
          curl -F package=@$filename https://${FURY_TOKEN}@push.fury.io/qucheng/
        done
